name: build test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"

      - name: dependencies
        run: npm install

      - name: build
        run: npm run build
